import 'package:task_notes_app_fixed/constants.dart';

/// Data model for task items with JSON serialization support
///
/// This class represents a task with its essential properties including
/// title, priority level, description, and completion status.

class TaskItem {
  /// Unique identifier for the task (auto-generated by database)
  final int? id;

  /// Task title (required field)
  final String title;

  /// Priority level: must be one of AppConstants.priorityOptions
  final String priority;

  /// Optional detailed description of the task
  final String description;

  /// Completion status of the task
  final bool isCompleted;

  /// Constructor for creating a new TaskItem
  TaskItem({
    this.id,
    required this.title,
    required this.priority,
    required this.description,
    required this.isCompleted,
  });

  /// Creates a TaskItem instance from a JSON map
  /// Used when loading data from database or external sources
  factory TaskItem.fromJson(Map<String, dynamic> json) {
    return TaskItem(
      id: json[AppConstants.idColumn] as int?,
      title: json[AppConstants.titleColumn] as String,
      priority: json[AppConstants.priorityColumn] as String,
      description: json[AppConstants.descriptionColumn] as String? ?? '',
      isCompleted: (json[AppConstants.isCompletedColumn] as int) == 1,
    );
  }

  /// Converts TaskItem to JSON map for database storage
  /// Note: isCompleted is stored as integer (0 or 1) for SQLite compatibility
  Map<String, dynamic> toJson() {
    return {
      AppConstants.idColumn: id,
      AppConstants.titleColumn: title,
      AppConstants.priorityColumn: priority,
      AppConstants.descriptionColumn: description,
      AppConstants.isCompletedColumn: isCompleted ? 1 : 0,
    };
  }

  /// Creates a copy of this TaskItem with optional field updates
  TaskItem copyWith({
    int? id,
    String? title,
    String? priority,
    String? description,
    bool? isCompleted,
  }) {
    return TaskItem(
      id: id ?? this.id,
      title: title ?? this.title,
      priority: priority ?? this.priority,
      description: description ?? this.description,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }

  /// Returns string representation for debugging
  @override
  String toString() {
    return 'TaskItem(id: $id, title: $title, priority: $priority, isCompleted: $isCompleted)';
  }

  /// Equality comparison based on id and content
  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is TaskItem &&
        other.id == id &&
        other.title == title &&
        other.priority == priority &&
        other.description == description &&
        other.isCompleted == isCompleted;
  }

  /// Hash code for efficient collection operations
  @override
  int get hashCode {
    return Object.hash(id, title, priority, description, isCompleted);
  }
}