// File generated by FlutterFire CLI, with modifications for web deployment
// https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // IMPORTANT: Update these with your Firebase project credentials
    // Get these values from Firebase Console > Project Settings
    return const FirebaseOptions(
      apiKey: String.fromEnvironment('FIREBASE_API_KEY', defaultValue: ''),
      appId: String.fromEnvironment('FIREBASE_APP_ID', defaultValue: ''),
      messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: ''),
      projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: ''),
      authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: ''),
      storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: ''),
      measurementId: String.fromEnvironment('FIREBASE_MEASUREMENT_ID', defaultValue: ''),
    );
  }
}
